const D=window.CONE_DATA,book=document.querySelector('#book');
const footer=()=>'<footer class="gz-footer"><div class="f1">'+D.footer[0]+'</div><div class="f2">'+D.footer[1]+'</div></footer>';
const p1=document.createElement('section');p1.className='page';p1.dataset.kind='student';p1.innerHTML='<div class="source-sheet">'+D.page1+'</div>'+footer();book.append(p1);
const p2=document.createElement('section');p2.className='page';p2.dataset.kind='student';p2.innerHTML='<header class="page-header"><h1>היכרות עם החרוט</h1><b>2</b></header><div class="hero"><div><div class="definition">חרוט הוא גוף המורכב מעיגול ונקודה שמחוץ למישור העיגול וכל הקטעים המחברים את הנקודה עם נקודות הנמצאות על היקף העיגול (מעגל). הנקודה נקראת קודקוד החרוט, העיגול נקרא בסיס החרוט. כל הקטעים הנ"ל יוצרים מעטפת החרוט.</div><div class="task">'+D.questions[0].prompt+' <span class="answer-line"></span></div><div class="task">'+D.questions[1].prompt+'</div></div><svg class="cone-svg" viewBox="0 0 420 470"><ellipse cx="210" cy="370" rx="150" ry="45" fill="#f8fafc" stroke="#1d4ed8" stroke-width="4"/><path d="M210 45 L60 370 M210 45 L360 370" fill="none" stroke="#1d4ed8" stroke-width="4"/><line x1="210" y1="45" x2="210" y2="370" stroke="#475569" stroke-width="3" stroke-dasharray="7 6"/><line x1="210" y1="370" x2="360" y2="370" stroke="#111827" stroke-width="3"/><text class="label" x="224" y="210">h</text><text class="label" x="282" y="358">r</text></svg></div>'+footer();book.append(p2);
const p3=document.createElement('section');p3.className='page';p3.dataset.kind='student';p3.innerHTML='<header class="page-header"><h1>נפח חרוט — השלימו: V = ________</h1><b>3</b></header><div class="task">'+D.questions[2].prompt+'</div><div class="work-grid"></div><div class="task">'+D.questions[3].prompt+'</div><table class="practice-table"><tr><th>r</th><th>d</th><th>h</th><th>V</th></tr><tr><td>3</td><td></td><td>8</td><td></td></tr><tr><td></td><td>8</td><td>12</td><td></td></tr><tr><td>5</td><td></td><td>12</td><td></td></tr></table>'+footer();book.append(p3);
const p4=document.createElement('section');p4.className='page';p4.dataset.kind='student';p4.innerHTML='<header class="page-header"><h1>חתך צירי ומשפט פיתגורס</h1><b>4</b></header><div class="task">'+D.questions[4].prompt+'</div><div class="work-grid"></div><div class="task">'+D.questions[5].prompt+'</div><div class="work-grid"></div>'+footer();book.append(p4);
const tp=document.createElement('section');tp.className='page teacher-page';tp.dataset.kind='teacher';tp.innerHTML='<header class="page-header"><h1>פתרונות למורה</h1><b>מורה</b></header>'+D.questions.map(q=>'<div class="teacher-answer"><strong>'+q.id+'</strong><div>'+q.answer+'</div></div>').join('')+footer();book.append(tp);
let teacher=false,idx=0;const students=[...document.querySelectorAll('[data-kind="student"]')],teachers=[...document.querySelectorAll('[data-kind="teacher"]')];
function show(){students.forEach((p,i)=>p.hidden=teacher||i!==idx);teachers.forEach(p=>p.hidden=!teacher);document.querySelector('#counter').textContent=teacher?'פתרונות למורה':(idx+1)+' / '+students.length}
document.querySelector('#prev').onclick=()=>{idx=Math.max(0,idx-1);show()};document.querySelector('#next').onclick=()=>{idx=Math.min(students.length-1,idx+1);show()};document.querySelector('#teacher').onclick=()=>{teacher=!teacher;show()};show();